// Unit tests for the C++ port. The test cases mirror the Java
// TeenPattiAlgorithmUtilTest one-to-one (and the Go algorithm_test.go), plus a
// full-table consistency check: every one of the 23479 entries of the
// Java-generated teenpatti_data.txt must be reproduced by this port.
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <teenpatti/teenpatti.hpp>

#ifndef TEENPATTI_TEST_DATA_PATH
#define TEENPATTI_TEST_DATA_PATH "teenpatti_data.txt"
#endif

namespace {

int g_failures = 0;

void expect_true(bool cond, const std::string& msg) {
  if (!cond) {
    std::printf("  FAIL: %s\n", msg.c_str());
    ++g_failures;
  }
}

void expect_eq(long long got, long long want, const std::string& msg) {
  if (got != want) {
    std::printf("  FAIL: %s (got %lld, want %lld)\n", msg.c_str(), got, want);
    ++g_failures;
  }
}

void test_case(const char* name, void (*fn)()) {
  std::printf("[ RUN      ] %s\n", name);
  const int before = g_failures;
  fn();
  if (g_failures == before) {
    std::printf("[       OK ] %s\n", name);
  } else {
    std::printf("[  FAILED  ] %s\n", name);
  }
}

// Mirrors Java testHandEvaluation.
void test_hand_evaluation() {
  const std::string cards = "黑A,方A,鬼";
  const std::string cards1 = "黑A,鬼,方3";

  // "黑A,方A,鬼" can form AAA (Trail / Three of a kind, type 6)
  expect_eq(teenpatti::get_win_type(cards), 6, "AAA should be trail (type 6)");

  const int pos_cards = teenpatti::get_win_position(cards);
  const int pos_cards1 = teenpatti::get_win_position(cards1);
  expect_true(pos_cards > 0, "Position should be positive");
  expect_true(pos_cards1 > 0, "Position should be positive");
  expect_true(pos_cards > pos_cards1, "AAA should rank higher than AK3");

  expect_true(teenpatti::compare(cards, cards1) > 0, "cards should win against cards1");
}

// Mirrors Java testCompareEqual.
void test_compare_equal() {
  const std::string cards_a = "黑A,方K,梅Q";
  const std::string cards_b = "红A,梅K,方Q";
  expect_eq(teenpatti::compare(cards_a, cards_b), 0, "Hands of same rank should tie");
}

// Mirrors Java testGetMaxAndKeyToStr.
void test_get_max_and_key_to_str() {
  const int max_key = teenpatti::get_max("黑A,方A,鬼");
  expect_true(max_key > 0, "maxKey should be positive");

  const std::string max_str = teenpatti::key_to_str(max_key);
  expect_true(!max_str.empty(), "maxStr should not be empty");
  expect_true(max_str.find('A') != std::string::npos,
              "Resolved max card string should contain A");
}

// Mirrors Java testKeyDataGetters.
void test_key_data_getters() {
  const auto kd = teenpatti::get_key_data(teenpatti::str_to_pokes("黑A,方A,鬼"));
  expect_true(kd.has_value(), "KeyData should be present");
  if (!kd) {
    return;
  }
  expect_eq(kd->type, 6, "Type should be 6");
  expect_true(kd->max > 0, "Max should be positive");
  expect_eq(kd->position,
            teenpatti::get_win_position(teenpatti::str_to_pokes("黑A,方A,鬼")),
            "Position should match get_win_position");
}

// Mirrors Java testInvalidHand.
void test_invalid_hand() {
  expect_eq(teenpatti::get_win_position("黑A,方A"), 0, "get_win_position should be 0");
  expect_eq(teenpatti::get_win_type("黑A,方A"), 0, "get_win_type should be 0");
  expect_eq(teenpatti::get_max("黑A,方A"), 0, "get_max should be 0");
}

// Documents the Java-compatible behavior of the string overload of
// get_key_data, which only accepts 7-card hands.
void test_get_key_data_requires_seven_cards() {
  expect_true(!teenpatti::get_key_data(std::string("黑A,方A,鬼")).has_value(),
              "get_key_data with 3 cards should return nullopt (Java parity)");
}

// Checks that the generation pipeline enumerates every distinct 3-card hand
// of the 55-card deck.
void test_gen_key_enumerates_all_hands() {
  teenpatti::gen_key();
  expect_eq(static_cast<long long>(teenpatti::gen_keys().size()), 23479,
            "expected 23479 distinct keys");
}

// Verifies that teenpatti_data.txt (generated by the Java implementation) is
// fully reproduced by this port: for every entry the rank, type, best-hand
// key and readable strings recomputed by the C++ algorithm must match.
void test_data_table_consistency() {
  std::ifstream f(TEENPATTI_TEST_DATA_PATH, std::ios::binary);
  expect_true(static_cast<bool>(f), "open teenpatti_data.txt");
  if (!f) {
    return;
  }

  int total = 0;
  std::string line;
  while (std::getline(f, line)) {
    if (!line.empty() && line.back() == '\r') {
      line.pop_back();
    }
    if (line.empty()) {
      continue;
    }
    std::vector<std::string> fields;
    std::string item;
    std::istringstream iss(line);
    while (std::getline(iss, item, ' ')) {
      fields.push_back(item);
    }
    expect_true(fields.size() >= 8, "malformed line: " + line);
    if (fields.size() < 8) {
      return;
    }

    const int key = std::stoi(fields[0]);
    const int pos = std::stoi(fields[1]);
    const int typ = std::stoi(fields[5]);
    const int max = std::stoi(fields[6]);
    const std::string& str = fields[4];
    const std::string& max_str = fields[7];

    const auto kd = teenpatti::get_key_data(key);
    expect_true(kd.has_value(), "key missing from loaded table: " + std::to_string(key));
    if (!kd) {
      return;
    }
    expect_eq(kd->position, pos, "position mismatch for key " + std::to_string(key));
    expect_eq(kd->type, typ, "type mismatch for key " + std::to_string(key));
    expect_eq(kd->max, max, "max mismatch for key " + std::to_string(key));
    expect_true(teenpatti::key_to_str(key) == str, "key string mismatch for key " + std::to_string(key));
    expect_true(teenpatti::key_to_str(kd->max) == max_str,
                "max string mismatch for key " + std::to_string(key));

    // Recompute the best hand from scratch through the card utils.
    expect_eq(teenpatti::gen_poke_card_bind(teenpatti::max_cards(teenpatti::key_to_pokes(key))),
              max, "recomputed max mismatch for key " + std::to_string(key));
    expect_eq(teenpatti::get_card_type_unordered(teenpatti::max_cards(teenpatti::key_to_pokes(key))),
              typ, "recomputed max type mismatch for key " + std::to_string(key));

    // The byte form must round-trip through get_key_data's vector overload.
    const auto resolved = teenpatti::get_key_data(teenpatti::key_to_bytes(key));
    expect_true(resolved.has_value() && resolved->position == kd->position &&
                    resolved->type == kd->type && resolved->max == kd->max,
                "key does not round-trip: " + std::to_string(key));
    ++total;
  }
  expect_eq(total, 23479, "expected 23479 table entries");
}

}  // namespace

int main() {
  // Mirrors the Java @BeforeAll setup: load the table and assert non-empty.
  if (!teenpatti::load()) {
    std::printf("FAIL: load() failed\n");
    return 1;
  }
  if (teenpatti::normal_map()->empty()) {
    std::printf("FAIL: normal_map should not be empty after load\n");
    return 1;
  }

  test_case("TestHandEvaluation", test_hand_evaluation);
  test_case("TestCompareEqual", test_compare_equal);
  test_case("TestGetMaxAndKeyToStr", test_get_max_and_key_to_str);
  test_case("TestKeyDataGetters", test_key_data_getters);
  test_case("TestInvalidHand", test_invalid_hand);
  test_case("TestGetKeyDataRequiresSevenCards", test_get_key_data_requires_seven_cards);
  test_case("TestDataTableConsistency", test_data_table_consistency);
  test_case("TestGenKeyEnumeratesAllHands", test_gen_key_enumerates_all_hands);

  if (g_failures != 0) {
    std::printf("%d FAILURE(S)\n", g_failures);
    return 1;
  }
  std::printf("ALL TESTS PASSED\n");
  return 0;
}
