package teenpatti

import (
	"bufio"
	"strconv"
	"strings"
	"testing"
)

// TestDataTableConsistency verifies that the embedded teenpatti_data.txt
// (generated by the Java implementation) is fully reproduced by this Go
// port: for every one of the 23479 entries the rank, type, best-hand key and
// readable strings recomputed by the Go algorithm must match the table.
func TestDataTableConsistency(t *testing.T) {
	data, err := teenPattiData.ReadFile("teenpatti_data.txt")
	if err != nil {
		t.Fatalf("read embedded data: %v", err)
	}

	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)

	total := 0
	for scanner.Scan() {
		line := strings.TrimRight(scanner.Text(), "\r")
		if line == "" {
			continue
		}
		fields := strings.Split(line, " ")
		if len(fields) < 8 {
			t.Fatalf("malformed line: %q", line)
		}
		key, err := strconv.Atoi(fields[0])
		if err != nil {
			t.Fatalf("bad key in line %q: %v", line, err)
		}
		pos, err := strconv.Atoi(fields[1])
		if err != nil {
			t.Fatalf("bad position in line %q: %v", line, err)
		}
		typ, err := strconv.Atoi(fields[5])
		if err != nil {
			t.Fatalf("bad type in line %q: %v", line, err)
		}
		max, err := strconv.Atoi(fields[6])
		if err != nil {
			t.Fatalf("bad max in line %q: %v", line, err)
		}
		str := fields[4]
		maxStr := fields[7]

		kd := GetKeyDataByKey(key)
		if kd == nil {
			t.Fatalf("key %d missing from loaded table", key)
		}
		if kd.Position != pos {
			t.Fatalf("key %d position: table %d, computed %d", key, pos, kd.Position)
		}
		if kd.Type != typ {
			t.Fatalf("key %d type: table %d, computed %d", key, typ, kd.Type)
		}
		if kd.Max != max {
			t.Fatalf("key %d max: table %d, computed %d", key, max, kd.Max)
		}
		if KeyToStr(key) != str {
			t.Fatalf("key %d string: table %q, computed %q", key, str, KeyToStr(key))
		}
		if KeyToStr(kd.Max) != maxStr {
			t.Fatalf("key %d max string: table %q, computed %q", key, maxStr, KeyToStr(kd.Max))
		}

		// Recompute the best hand from scratch through the card utils.
		cards := KeyToPokes(key)
		if got := GenPokeCardBind(MaxCards(cards)); got != max {
			t.Fatalf("key %d recomputed max: table %d, computed %d", key, max, got)
		}
		if got := GetCardTypeUnordered(MaxCards(cards)); got != typ {
			t.Fatalf("key %d recomputed max type: table %d, computed %d", key, typ, got)
		}

		// The byte form must round-trip through the same path used by
		// GetKeyDataByCards.
		pokes := KeyToBytes(key)
		resolved := GetKeyDataByCards(pokes)
		if resolved == nil || *resolved != *kd {
			t.Fatalf("key %d does not round-trip via GetKeyDataByCards", key)
		}
		total++
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan data: %v", err)
	}
	if total != 23479 {
		t.Fatalf("expected 23479 table entries, verified %d", total)
	}
}
